### ISSUE TITLE
Create better UI for title/main menu screen

### ISSUE THREAD

**Issue by Kynot54** [Kynot54/tic-tac-toe-21#2]
What we had previously discussed on discord...

**Comment by ethanl21** [comment]
As a player, I want to be presented with an attractive menu screen so that would make me want to play our game.

This story can be considered done when players are presented with an attractive start screen upon launching our app, featuring custom graphics and responsive UI styling.

Tasks that need to be completed in order for this story to be done include:
- [ ] Create graphics for the game's logo
- [ ] Create themed buttons so that we aren't using the default Godot Engine buttons
- [ ] Create an app icon
- [ ] Configure the UI to scale to different device resolutions and aspect ratios, presented vertically and growing upwards
- [ ] Create a Theme that can be reused elsewhere to give our game a consistent look

I anticipate this should be simple, with the responsive UI step taking the most time.
