### ISSUE TITLE
Create transition from main menu / title scene to player's hand. (Beginning of first round of 21).

### ISSUE THREAD

**Issue by Kynot54** [Kynot54/tic-tac-toe-21#3]
As mentioned before on discord.

**Comment by ethanl21** [comment]
As a player, I should be able to press a button to initiate a game.

For this story to be considered done, players should be able to begin our game by pressing a button to transition to the 21 phase. It should be obvious to the player that they have transitioned to the gameplay portion of our app and that a round has begun.

Tasks include:
- [ ] Linking the start button on the main menu to an event that starts the game
- [ ] Adding a smooth transition between the menu scene and the 21 scene
- [ ] Indicating that the game has begun by using graphics, text, or otherwise.

Blockers include:
- [ ] Creating the main menu screen #2 , this needs to be done first
- [ ] Creating a 21 scene (can be blank if necessary)

This issue is blocked by #2 , and should be simple to implement after it is completed.

**Comment by ethanl21** [comment]
I need to configure SceneTransitionRect to wait for the scene to be finished loading before revealing the scene so assets don't pop in, otherwise this issue is complete.
- [ ] Wait for scene to be finished before revealing it
